<?xml version="1.0" encoding="utf-8"?><Database Name="Storage" Class="StorageDataContext" AccessModifier="Internal" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(LocalDB)\v11.0;AttachDbFilename=&quot;C:\Users\Vladimir\documents\visual studio 2013\Projects\CashMachine\CashMachine\App_Data\Storage.mdf&quot;;Integrated Security=True" SettingsObjectName="CashMachine.Storage.Properties.Settings" SettingsPropertyName="StorageConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Cards" Member="Cards" AccessModifier="Internal">
    <Type Name="Card" AccessModifier="Internal">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Number" Type="System.String" DbType="NVarChar(16) NOT NULL" CanBeNull="false" />
      <Column Name="HashedPin" Type="System.String" DbType="NVarChar(32) NOT NULL" CanBeNull="false" />
      <Column Name="Balance" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="WrongAttempts" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IsValid" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="Card_Operation" Member="Operations" AccessModifier="Internal" ThisKey="Id" OtherKey="CardId" Type="Operation" />
    </Type>
  </Table>
  <Table Name="dbo.Operations" Member="Operations" AccessModifier="Internal">
    <Type Name="Operation" AccessModifier="Internal">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CardId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="OperationCode" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Amount" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="Timestamp" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="Card_Operation" Member="Card" AccessModifier="Internal" ThisKey="CardId" OtherKey="Id" Type="Card" IsForeignKey="true" />
    </Type>
  </Table>
</Database>